"""rankings and why bullets

Revision ID: 1be0604ef833
Revises: 7f22459b036d
Create Date: 2026-08-30 10:23:41.239762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1be0604ef833'
down_revision: Union[str, Sequence[str], None] = '7f22459b036d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rankings',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=4), nullable=False),
    sa.Column('team', sa.String(length=4), nullable=True),
    sa.Column('overall_rank', sa.Integer(), nullable=True),
    sa.Column('pos_rank', sa.Integer(), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('value_tier', sa.Integer(), nullable=True),
    sa.Column('ppg_vendor', sa.Float(), nullable=True),
    sa.Column('ppg_inhouse', sa.Float(), nullable=True),
    sa.Column('ppg_inhouse_raw', sa.Float(), nullable=True),
    sa.Column('w_vendor', sa.Float(), nullable=True),
    sa.Column('w_inhouse', sa.Float(), nullable=True),
    sa.Column('bonus_pg', sa.Float(), nullable=True),
    sa.Column('ppg_blend', sa.Float(), nullable=True),
    sa.Column('e_games', sa.Float(), nullable=True),
    sa.Column('replacement_ppg', sa.Float(), nullable=True),
    sa.Column('baseline_rank', sa.Integer(), nullable=True),
    sa.Column('season_value', sa.Float(), nullable=True),
    sa.Column('vols', sa.Float(), nullable=True),
    sa.Column('vorp', sa.Float(), nullable=True),
    sa.Column('ecr', sa.Float(), nullable=True),
    sa.Column('ecr_sd', sa.Float(), nullable=True),
    sa.Column('disagreement', sa.Float(), nullable=True),
    sa.Column('yahoo_adp', sa.Float(), nullable=True),
    sa.Column('ffc_adp', sa.Float(), nullable=True),
    sa.Column('sleeper_adp', sa.Float(), nullable=True),
    sa.Column('composite_adp', sa.Float(), nullable=True),
    sa.Column('room_adp', sa.Float(), nullable=True),
    sa.Column('sd_adp', sa.Float(), nullable=True),
    sa.Column('sd_adp_source', sa.String(length=8), nullable=True),
    sa.Column('our_pick_equivalent', sa.Float(), nullable=True),
    sa.Column('gap', sa.Float(), nullable=True),
    sa.Column('gap_z', sa.Float(), nullable=True),
    sa.Column('p_avail_next', sa.Float(), nullable=True),
    sa.Column('vona', sa.Float(), nullable=True),
    sa.Column('flags', postgresql.ARRAY(sa.String(length=32)), nullable=True),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_kdst', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['ranking_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'player_id')
    )
    op.create_index('ix_rankings_run_overall', 'rankings', ['run_id', 'overall_rank'], unique=False)
    op.create_table('why_bullets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=48), nullable=False),
    sa.Column('template_version', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('polarity', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('seasons', sa.String(length=24), nullable=True),
    sa.Column('snapshot_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['ranking_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_why_bullets_run_player', 'why_bullets', ['run_id', 'player_id', 'priority'], unique=False)
    op.add_column('ranking_runs', sa.Column('status', sa.String(length=16), nullable=False))
    op.add_column('ranking_runs', sa.Column('model_version', sa.String(length=24), nullable=True))
    op.add_column('ranking_runs', sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('ranking_runs', sa.Column('keepers_hash', sa.String(length=64), nullable=True))
    op.add_column('ranking_runs', sa.Column('spearman_top150', sa.Float(), nullable=True))
    op.add_column('ranking_runs', sa.Column('n_players_ranked', sa.Integer(), nullable=True))
    op.add_column('ranking_runs', sa.Column('n_why_bullets', sa.Integer(), nullable=True))
    op.add_column('ranking_runs', sa.Column('duration_s', sa.Float(), nullable=True))
    op.add_column('ranking_runs', sa.Column('error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ranking_runs', 'error')
    op.drop_column('ranking_runs', 'duration_s')
    op.drop_column('ranking_runs', 'n_why_bullets')
    op.drop_column('ranking_runs', 'n_players_ranked')
    op.drop_column('ranking_runs', 'spearman_top150')
    op.drop_column('ranking_runs', 'keepers_hash')
    op.drop_column('ranking_runs', 'weights')
    op.drop_column('ranking_runs', 'model_version')
    op.drop_column('ranking_runs', 'status')
    op.drop_index('ix_why_bullets_run_player', table_name='why_bullets')
    op.drop_table('why_bullets')
    op.drop_index('ix_rankings_run_overall', table_name='rankings')
    op.drop_table('rankings')
    # ### end Alembic commands ###
