"""rankings is_keeper

Revision ID: 22867d6592f7
Revises: 1be0604ef833
Create Date: 2026-08-30 12:09:31.482455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22867d6592f7'
down_revision: Union[str, Sequence[str], None] = '1be0604ef833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # rankings is a derived table rebuilt by `ff rank run`; existing rows predate the column
    op.add_column('rankings', sa.Column('is_keeper', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rankings', 'is_keeper')
    # ### end Alembic commands ###
