"""provenance tables

Revision ID: 6b975fffbc37
Revises: 
Create Date: 2026-08-29 18:13:43.877606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b975fffbc37'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranking_runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('git_sha', sa.String(length=40), nullable=True),
    sa.Column('league_config_sha256', sa.String(length=64), nullable=False),
    sa.Column('seed_hashes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_snapshot_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_frozen', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index('ix_raw_snapshots_sha', 'raw_snapshots', ['source', 'endpoint', 'sha256'], unique=False)
    op.create_index('ix_raw_snapshots_source_endpoint_fetched', 'raw_snapshots', ['source', 'endpoint', 'fetched_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('raw_snapshots')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_raw_snapshots_source_endpoint_fetched', table_name='raw_snapshots')
    op.drop_index('ix_raw_snapshots_sha', table_name='raw_snapshots')
    op.drop_table('ranking_runs')
    # ### end Alembic commands ###
