"""team context

Revision ID: 7f22459b036d
Revises: aa3bea6efb56
Create Date: 2026-08-30 08:25:43.952869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f22459b036d'
down_revision: Union[str, Sequence[str], None] = 'aa3bea6efb56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_context',
    sa.Column('team', sa.String(length=4), nullable=False),
    sa.Column('hc', sa.Text(), nullable=True),
    sa.Column('hc_new', sa.Boolean(), nullable=False),
    sa.Column('hc_since', sa.Integer(), nullable=True),
    sa.Column('oc', sa.Text(), nullable=True),
    sa.Column('oc_new', sa.Boolean(), nullable=False),
    sa.Column('dc', sa.Text(), nullable=True),
    sa.Column('dc_new', sa.Boolean(), nullable=False),
    sa.Column('play_caller', sa.Text(), nullable=True),
    sa.Column('play_caller_role', sa.String(length=16), nullable=True),
    sa.Column('play_caller_2025', sa.Text(), nullable=True),
    sa.Column('play_caller_new', sa.Boolean(), nullable=False),
    sa.Column('projected_qb1', sa.Text(), nullable=True),
    sa.Column('qb1_2025', sa.Text(), nullable=True),
    sa.Column('qb_changed_from_2025', sa.Boolean(), nullable=False),
    sa.Column('qb_status', sa.String(length=16), nullable=True),
    sa.Column('qb_quality_tier', sa.Integer(), nullable=True),
    sa.Column('qb_backup', sa.Text(), nullable=True),
    sa.Column('ol_delta', sa.Integer(), nullable=True),
    sa.Column('ol_rank_2026', sa.Integer(), nullable=True),
    sa.Column('ol_adds', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ol_losses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ol_injuries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ol_r1_pick', sa.Text(), nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_checked', sa.Date(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('seed_hashes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('warning', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('team')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_context')
    # ### end Alembic commands ###
