"""draft tables

Revision ID: 922a18147264
Revises: c87fe11bda73
Create Date: 2026-08-29 18:21:08.531548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '922a18147264'
down_revision: Union[str, Sequence[str], None] = 'c87fe11bda73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('league_key', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('num_teams', sa.Integer(), nullable=False),
    sa.Column('rounds', sa.Integer(), nullable=False),
    sa.Column('draft_type', sa.String(length=16), nullable=False),
    sa.Column('draft_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('draft_status', sa.String(length=16), nullable=False),
    sa.Column('draft_order', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('my_team_slot', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('draft_picks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('overall_pick', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('team_slot', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('external_player_key', sa.String(length=32), nullable=True),
    sa.Column('is_keeper', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=12), nullable=False),
    sa.Column('picked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('undone_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_draft_picks_league_pick', 'draft_picks', ['league_id', 'overall_pick'], unique=False)
    op.create_index('uq_draft_picks_active', 'draft_picks', ['league_id', 'overall_pick'], unique=True, postgresql_where='undone_at IS NULL')
    op.create_table('keepers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('team_slot', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('cost_round', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('source', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'player_id', name='uq_keepers_player'),
    sa.UniqueConstraint('league_id', 'team_slot', 'cost_round', name='uq_keepers_slot_round')
    )
    op.create_table('pick_schedule',
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('overall_pick', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('team_slot', sa.Integer(), nullable=False),
    sa.Column('is_keeper_slot', sa.Boolean(), nullable=False),
    sa.Column('keeper_player_id', sa.Integer(), nullable=True),
    sa.Column('live_pick_no', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['keeper_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('league_id', 'overall_pick')
    )
    op.drop_table('raw_nflverse_injuries')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_ffc_adp',
    sa.Column('player_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('position', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('team', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('adp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('adp_formatted', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('times_drafted', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('high', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('low', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('stdev', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bye', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('format', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('teams', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('rounds', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('total_drafts', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('year', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('snapshot_id', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_table('pick_schedule')
    op.drop_table('keepers')
    op.drop_index('uq_draft_picks_active', table_name='draft_picks', postgresql_where='undone_at IS NULL')
    op.drop_index('ix_draft_picks_league_pick', table_name='draft_picks')
    op.drop_table('draft_picks')
    op.drop_table('leagues')
    # ### end Alembic commands ###
