"""rank snapshots

Revision ID: aa3bea6efb56
Revises: 922a18147264
Create Date: 2026-08-30 08:14:05.502727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa3bea6efb56'
down_revision: Union[str, Sequence[str], None] = '922a18147264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rank_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('rank', sa.Float(), nullable=True),
    sa.Column('adp', sa.Float(), nullable=True),
    sa.Column('std', sa.Float(), nullable=True),
    sa.Column('min_pick', sa.Float(), nullable=True),
    sa.Column('max_pick', sa.Float(), nullable=True),
    sa.Column('n', sa.Integer(), nullable=True),
    sa.Column('pct_drafted', sa.Float(), nullable=True),
    sa.Column('bye', sa.Integer(), nullable=True),
    sa.Column('as_of', sa.Date(), nullable=True),
    sa.Column('snapshot_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'source', 'format', 'snapshot_id', name='uq_rank_snapshots_player_source_snap')
    )
    op.create_index('ix_rank_snapshots_source_asof', 'rank_snapshots', ['source', 'format', 'as_of'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rank_snapshots_source_asof', table_name='rank_snapshots')
    op.drop_table('rank_snapshots')
    # ### end Alembic commands ###
