"""players hub

Revision ID: c87fe11bda73
Revises: 6b975fffbc37
Create Date: 2026-08-29 18:19:55.547378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c87fe11bda73'
down_revision: Union[str, Sequence[str], None] = '6b975fffbc37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gsis_id', sa.String(length=16), nullable=True),
    sa.Column('esb_id', sa.String(length=16), nullable=True),
    sa.Column('sleeper_id', sa.String(length=16), nullable=True),
    sa.Column('espn_id', sa.String(length=16), nullable=True),
    sa.Column('yahoo_id', sa.String(length=16), nullable=True),
    sa.Column('fantasypros_id', sa.String(length=16), nullable=True),
    sa.Column('pfr_id', sa.String(length=16), nullable=True),
    sa.Column('otc_id', sa.String(length=16), nullable=True),
    sa.Column('stats_id', sa.String(length=16), nullable=True),
    sa.Column('yahoo_player_key', sa.String(length=24), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('name_norm', sa.String(length=80), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=True),
    sa.Column('last_name', sa.String(length=40), nullable=True),
    sa.Column('position', sa.String(length=4), nullable=False),
    sa.Column('team', sa.String(length=4), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('years_exp', sa.Integer(), nullable=True),
    sa.Column('draft_year', sa.Integer(), nullable=True),
    sa.Column('draft_round', sa.Integer(), nullable=True),
    sa.Column('draft_pick', sa.Integer(), nullable=True),
    sa.Column('draft_team', sa.String(length=4), nullable=True),
    sa.Column('is_rookie', sa.Boolean(), nullable=False),
    sa.Column('college', sa.String(length=80), nullable=True),
    sa.Column('match_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gsis_id')
    )
    op.create_index('ix_players_fantasypros_id', 'players', ['fantasypros_id'], unique=False)
    op.create_index('ix_players_name_norm_pos', 'players', ['name_norm', 'position'], unique=False)
    op.create_index('ix_players_sleeper_id', 'players', ['sleeper_id'], unique=False)
    op.create_index('ix_players_yahoo_id', 'players', ['yahoo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_players_yahoo_id', table_name='players')
    op.drop_index('ix_players_sleeper_id', table_name='players')
    op.drop_index('ix_players_name_norm_pos', table_name='players')
    op.drop_index('ix_players_fantasypros_id', table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
